name: sweep_ft
method: random
metric:
  goal: maximize
  name: Average Test Accuracy
parameters:
  learning_rate:
    values: [1e-1, 1e-2, 1e-3]
  batch_size:
    values: [4, 8]
  epochs:
    values: [20, 30, 50]
  weight_decay:
    values: [0.0, 1e-4, 1e-3]
  dropout:
    values: [0.01, 0.05, 0.1]
  train_steps:
    values: [100]